"use client";

import { useEffect, useState } from "react";
import { SprayDataProfile } from "../../services/SprayDataProfile";

import ReactECharts from "echarts-for-react";
import "echarts-gl";

export default function MlbDashboard() {
  const [options, setOptions] = useState(null);

  useEffect(() => {
    const load = async () => {
      const profile = new SprayDataProfile(
        "/spray_data/FMX030-20_Z26.5(IN).txt"
      );
      await profile.loadData();
      profile.formatToEcharts();

      const xLabels = [
        ...new Set(profile.formattedMatrix.map(([, x]) => x - 62)),
      ];
      const yLabels = [
        ...new Set(profile.formattedMatrix.map(([, y]) => y - 62)),
      ];

      const min = profile.getMin();
      const max = profile.getMax();

      setOptions({
        xAxis3D: {
          type: "category",
          data: xLabels,
          axisLabel: {
            color: "#ffffff",
          },
          nameTextStyle: {
            color: "#ffffff",
          },
          axisPointer: {
            show: false,
          },
        },
        yAxis3D: {
          type: "category",
          name: "",
          data: yLabels,
          axisLabel: { show: false },
          axisTick: { show: false },
          axisPointer: {
            show: false,
          },
        },
        zAxis3D: {
          type: "value",
          axisLabel: {
            color: "#ffffff",
          },
          nameTextStyle: {
            color: "#ffffff",
          },
          axisPointer: {
            show: false,
          },
        },
        grid3D: {
          viewControl: {
            projection: "perspective",
            distance: 195,
            alpha: 5,
            beta: -1,
          },
        },
        visualMap: {
          min,
          max,
          show: false,
          orient: "horizontal",
          left: "center",
          bottom: "5%",
          inRange: {
            color: [
              "#0000ff", // blue
              "#00ffff", // cyan
              "#00ff00", // green
              "#ffff00", // yellow
              "#ff0000", // red
            ],
          },
        },
        tooltip: { show: false },
        series: [
          {
            type: "scatter3D",
            data: profile.formattedMatrix,
            label: {
              show: false,
            },
            emphasis: { disabled: true },
            animation: false,
          },
        ],
      });
    };

    load();
  }, []);
  return (
    <div className="min-h-screen flex flex-col bg-[url('/background_images/industrial_pipes.png')] bg-cover bg-center p-4">
      <div className="mt-14">
        <h1 className="text-4xl text-center">
          Introduction to Laser Sheet Imaging (LSI){" "}
        </h1>
      </div>
      <div>
        <section id="introduction" className="my-6 text-justify">
          <h2 className="text-3xl mb-3">Introduction</h2>
          <p>
            Understanding the behavior of sprays—how they form, spread, and
            interact with their environment—is critical across a wide range of
            industries, including fuel injection, agriculture, pharmaceuticals,
            and chemical processing. While these principles may be well known to
            professionals working in spray technology or fluid dynamics, this
            overview is intended to support engineers, researchers, and
            technical stakeholders who may be new to the field. Laser Sheet
            Imaging (LSI) provides a precise and non-intrusive method for
            visualizing and analyzing spray structures in high detail. A spray
            pattern of particular interest is the hydraulic full cone spray,
            frequently generated by industrial nozzles, due to its widespread
            use and performance-critical role in achieving uniform coverage,
            efficient atomization, and consistent delivery across applications.
            Along with the flat-fan spray, the hydraulic full cone spray
            represents one of the most commonly used spray patterns in
            industrial practice.
          </p>
        </section>
        <section id="introduction" className="my-6 text-justify">
          <h2 className="text-3xl mb-3">What is Laser Sheet Imaging?</h2>
          <p>
            Laser Sheet Imaging (LSI) is a non-intrusive optical method used to
            visualize and analyze the distribution of particles or droplets in a
            spray. The methodology involves projecting a thin sheet of laser
            light through the spray, where it interacts with transparent or
            refractive droplets. As the light scatters off these droplets, a
            camera captures the resulting intensity pattern, forming the basis
            for detailed spray analysis.
          </p>

          <p className="mt-2">Here’s how it works:</p>

          <ul className="mt-2 list-decimal pl-6 space-y-2">
            <li>
              A thin laser sheet is projected through a spray. This sheet acts
              like a planar “slice” through the spray volume.
            </li>
            <li>
              As the spray passes through the laser sheet, light scatters off
              the droplets.
            </li>
            <li>
              A camera captures the scattered light, creating a 2D image of
              droplet distribution.
            </li>
            <li>
              The brightness in the image corresponds to droplet concentration.
              Brighter areas generally indicate a higher number of droplets or
              larger droplet sizes, both of which contribute to increased
              surface area.
            </li>
            <li>
              The resulting image represents a 2D spatial distribution of
              droplets within the laser-illuminated plane. Unlike traditional
              physical collection methods, which often involve intrusive
              sampling hardware or disrupt the spray pattern, LSI offers a
              non-intrusive and faster alternative. This 2D data can be reduced
              to a 1D histogram to quantify key spray characteristics, enabling
              detailed analysis without interfering with the nozzle’s natural
              spray behavior.
            </li>
          </ul>

          <p className="mt-2">
            In conclusion, LSI provides a planar snapshot of the internal
            structure of a spray, allowing researchers and engineers to observe
            patterns such as droplet density, spray boundaries, and flow
            structure. By analyzing the resulting distribution, engineers can
            simulate spray overlaps. This is especially important in
            applications like spray coating, fuel injection, and agricultural
            spraying, where uniform coverage and controlled overlap are critical
            for performance and efficiency.
          </p>
        </section>

        <section id="introduction" className="my-6 text-justify">
          <h2 className="text-3xl mb-3">Methodology</h2>
          <div className="w-full max-w-[900px] aspect-[4/3] bg-red-400">
            {options && (
              <ReactECharts
                option={options}
                style={{
                  width: "100%",
                  height: "100%",
                }}
              />
            )}
          </div>
        </section>
      </div>
    </div>
  );
}
