"use client";

import { useEffect, useState } from "react";
import { SprayDataProfile } from "../../services/SprayDataProfile";

import Histogram from "./components/Histogram";

import ReactECharts from "echarts-for-react";
import "echarts-gl";

export default function SampleResearchDashboard() {
  const [options, setOptions] = useState(null);

  useEffect(() => {
    const load = async () => {
      const profile = new SprayDataProfile(
        "/spray_data/FMX030-20_Z20.5(IN).txt"
      );
      await profile.loadData();
      profile.formatToEcharts();

      const xLabels = [
        ...new Set(profile.formattedMatrix.map(([, x]) => x - 62)),
      ];
      const yLabels = [
        ...new Set(profile.formattedMatrix.map(([, y]) => y - 62)),
      ];

      const min = profile.getMin();
      const max = profile.getMax();

      setOptions({
        xAxis3D: {
          type: "value",
          data: xLabels,
          name: "X (mm)",
          axisLabel: {
            color: "#ffffff",
            formatter: function (val) {
              return val - 60;
            },
          },
          nameTextStyle: {
            color: "#ffffff",
          },
          axisPointer: {
            show: false,
          },
        },
        yAxis3D: {
          type: "category",
          name: "",
          data: yLabels,
          axisLabel: { show: false },
          axisTick: { show: false },
          axisPointer: {
            show: false,
          },
        },
        zAxis3D: {
          type: "value",
          name: "Light\nIntensitny",
          nameGap: 25,
          axisLabel: {
            color: "#ffffff",
          },
          nameTextStyle: {
            color: "#ffffff",
            align: "center",
          },
          axisPointer: {
            show: false,
          },
        },
        grid3D: {
          viewControl: {
            projection: "perspective",
            distance: 195,
            alpha: 5,
            beta: -1,
          },
        },
        visualMap: {
          min,
          max,
          show: false,
          orient: "horizontal",
          left: "center",
          bottom: "5%",
          inRange: {
            color: [
              "#0000ff", // blue
              "#00ffff", // cyan
              "#00ff00", // green
              "#ffff00", // yellow
              "#ff0000", // red
            ],
          },
        },
        tooltip: { show: false },
        series: [
          {
            type: "scatter3D",
            data: profile.formattedMatrix,
            label: {
              show: false,
            },
            emphasis: { disabled: true },
            animation: false,
          },
        ],
      });
    };

    load();
  }, []);
  return (
    <div className="min-h-screen flex flex-col bg-[url('/background_images/industrial_pipes.png')] bg-cover bg-center p-4">
      <div className="mt-20">
        <h1 className="text-4xl text-center">
          Introduction to Laser Sheet Imaging (LSI)
        </h1>
      </div>
      <div className="columns-1 lg:columns-2 gap-6 max-w-screen-xl mx-auto mt-12">
        <section
          id="introduction"
          className="mb-6 text-justify max-w-[800px] bg-[#222223] p-5 rounded-lg border border-gray-600 shadow-[inset_4px_4px_8px_rgba(255,255,255,0.1),_inset_-4px_-4px_8px_rgba(0,0,0,0.5)]"
        >
          <h2 className="text-3xl mb-3">Introduction</h2>
          <p>
            Understanding the behavior of sprays and how they form, spread, and
            interact with their environment is critical across a wide range of
            industries. These include fuel injection, agriculture,
            pharmaceuticals, and chemical processing.
          </p>
          <p className="mt-2">
            While these principles may be well known to professionals working in
            spray technology or fluid dynamics, this overview is intended to
            support engineers, researchers, and technical stakeholders who may
            be new to the field. Laser Sheet Imaging (LSI) provides a precise
            and non-intrusive method for visualizing and analyzing spray
            structures in high detail.
          </p>
          <p className="mt-2">
            One spray pattern of particular interest is the hydraulic full cone
            spray. It is frequently generated by industrial nozzles due to its
            widespread use and critical role in achieving uniform coverage,
            efficient atomization, and consistent delivery across applications.
            Along with the flat-fan spray, the hydraulic full cone spray is
            among the most commonly used spray patterns in industrial practice.
            Given its prevalence and importance across industries, we will use
            it as the subject of our characterization and testing.
          </p>
        </section>
        <section
          id="tool-familiarization"
          className="break-inside-avoid my-6 max-w-[800px] bg-[#222223] p-5 rounded-lg border border-gray-600 shadow-[inset_4px_4px_8px_rgba(255,255,255,0.1),_inset_-4px_-4px_8px_rgba(0,0,0,0.5)]"
        >
          <h2 className="text-3xl mb-3">What is Laser Sheet Imaging?</h2>
          <p className="text-justify">
            Laser Sheet Imaging (LSI) is a non-intrusive optical method used to
            visualize and analyze the distribution of particles or droplets in a
            spray. The methodology involves projecting a thin sheet of laser
            light through the spray, where it interacts with transparent or
            refractive droplets. As the light scatters off these droplets, a
            camera captures the resulting intensity pattern, forming the basis
            for detailed spray analysis.
          </p>

          <p className="mt-2 font-bold">Here’s how it works:</p>

          <ul className="mt-2 list-decimal pl-6 space-y-2">
            <li>
              A thin laser sheet is projected through a spray. This sheet acts
              like a planar “slice” through the spray volume.
            </li>
            <li>
              As the spray passes through the laser sheet, light scatters off
              the droplets.
            </li>
            <li>
              A camera captures the scattered light, creating a 2D image of
              droplet distribution.
            </li>
            <li>
              The brightness in the image corresponds to droplet concentration.
              Brighter areas generally indicate a higher number of droplets or
              larger droplet sizes, both of which contribute to increased
              surface area.
            </li>
            <li>
              The resulting image represents a 2D spatial distribution of
              droplets within the laser-illuminated plane. Unlike traditional
              physical collection methods, which often involve intrusive
              sampling hardware or disrupt the spray pattern, LSI offers a
              non-intrusive and faster alternative. This 2D data can be reduced
              to a 1D histogram to quantify key spray characteristics, enabling
              detailed analysis without interfering with the nozzle’s natural
              spray behavior.
            </li>
          </ul>

          <p className="mt-2">
            In conclusion, Laser Sheet Imaging (LSI) provides a planar snapshot
            of a spray’s internal structure. It allows researchers and engineers
            to observe features such as droplet density, spray boundaries, and
            flow patterns. By analyzing the resulting distribution, they can
            simulate spray overlaps. This is especially important in
            applications like spray coating, fuel injection, and agricultural
            spraying, where uniform coverage and controlled overlap are critical
            for both performance and efficiency.
          </p>
        </section>

        <section
          id="methodology"
          className="my-6 text-justify max-w-[800px] bg-[#222223] p-5 rounded-lg border border-gray-600 shadow-[inset_4px_4px_8px_rgba(255,255,255,0.1),_inset_-4px_-4px_8px_rgba(0,0,0,0.5)]"
        >
          <h2 className="text-3xl mb-3">Experimental Setup</h2>
          <p>
            A full cone nozzle was operated at a pressure of 20 psi, with the
            measurement plane positioned 20 inches downstream from the nozzle
            orifice. A thin laser sheet was projected perpendicularly through
            the spray at this location, illuminating a planar cross-section of
            the spray volume.
          </p>
          <p className="mt-2">
            A camera was positioned 45 degrees above the laser plane and
            downstream from the laser source. This angled setup allowed it to
            capture the scattered light intensity from the droplets. A total of
            500 successive images were recorded. These were then averaged to
            produce a single two-dimensional image representing the spatial
            distribution of droplets within the illuminated plane.
          </p>
        </section>

        <section
          id="results"
          className="break-inside-avoid my-6 text-justify max-w-[800px]"
        >
          <div className="bg-[#222223] p-5 rounded-lg border border-gray-600 shadow-[inset_4px_4px_8px_rgba(255,255,255,0.1),_inset_-4px_-4px_8px_rgba(0,0,0,0.5)]">
            <h2 className="text-3xl mb-3">Results</h2>
            <p className="mt-2">
              The 3D visualization of the spray data illustrates intensity as a
              function of position, offering a volumetric view of droplet
              concentration across the spray field. The results show that spray
              concentration is highest at the centerline of the nozzle and
              diminishes toward the outer edges. The data exhibits an
              exponential decrease in intensity from the center to the
              periphery, highlighting a significant difference in scale between
              the dense core and the outer spray regions. This contrast
              demonstrates how a full cone spray can quickly lose it&apos;s
              effectiveness over distance.
            </p>
          </div>
        </section>
        <div className="w-full max-w-[900px] aspect-[4/3] mt-4">
          {options && (
            <ReactECharts
              option={options}
              style={{
                width: "100%",
                height: "100%",
              }}
            />
          )}
        </div>

        <section className="my-6 text-justify max-w-[800px]">
          <div className="bg-[#222223] p-5 rounded-lg border border-gray-600 shadow-[inset_4px_4px_8px_rgba(255,255,255,0.1),_inset_-4px_-4px_8px_rgba(0,0,0,0.5)]">
            <p className="mt-2">
              To further analyze the spatial distribution, the 2D spray data,
              visualized in 3D, was collapsed into a single dimension by summing
              intensity values along the vertical (y) direction at each
              horizontal position. This process effectively reduces the
              volumetric dataset into a single horizontal profile, illustrating
              how droplet concentration varies across the width of the spray.
              The resulting histogram reveals the overall shape and symmetry of
              the spray pattern, making it easier to interpret centerline
              intensity and the rate of falloff toward the edges. This 1D
              profile also serves as a bridge to traditional patternator
              methods, which rely on physical droplet collection along a linear
              axis. In practice, full cone nozzles often produce a distribution
              that closely resembles a normal (Gaussian) curve, as shown below.
            </p>
          </div>

          <Histogram />
        </section>
        <section className="my-6 text-justify max-w-[800px]">
          <div className="bg-[#222223] p-5 rounded-lg border border-gray-600 shadow-[inset_4px_4px_8px_rgba(255,255,255,0.1),_inset_-4px_-4px_8px_rgba(0,0,0,0.5)]">
            <p className="mt-2">
              The symmetry of full-cone sprays makes them well-suited for
              predictable overlap in multi-nozzle systems. A common design
              guideline is to space nozzles at one-third of their spray width.
              This ensures that adjacent sprays overlap sufficiently to achieve
              uniform coverage without excessive redundancy or gaps. Such
              overlap considerations are especially important in applications
              like agricultural spraying and surface coating. Additional
              analysis can be performed by duplicating and shifting the one
              dimensional profile to simulate adjacent sprays. By comparing the
              combined profile to a uniform distribution, one can compute a
              coefficient of variation—assuming ideal conditions without plume
              interaction or droplet interference. However, this level of
              analysis will not be discussed here.
            </p>
          </div>
        </section>
        <section id="Conclusion" className="my-6 text-justify max-w-[800px]">
          <div className="bg-[#222223] p-5 rounded-lg border border-gray-600 shadow-[inset_4px_4px_8px_rgba(255,255,255,0.1),_inset_-4px_-4px_8px_rgba(0,0,0,0.5)]">
            <h2 className="text-3xl mb-3">Conclusion</h2>
            <p>
              The study demonstrates how Laser Sheet Imaging offers a powerful,
              non-intrusive technique for detailed visualization and analysis of
              full cone spray patterns. By capturing the spatial distribution of
              droplets within a laser-illuminated plane, LSI enables
              quantitative insights into spray structure, concentration
              gradients, and symmetry. The ability to reduce 2D spray data into
              meaningful single dimensional profiles facilitates comparison with
              traditional methods and supports design considerations for nozzle
              placement and spray overlap.
            </p>
            <p className="mt-2">
              Overall, LSI provides engineers and researchers with a robust tool
              to optimize spray performance across a variety of industrial
              applications, improving uniformity, efficiency, and control in
              processes that depend on precise spray behavior.
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
